In [1]:
import numpy as np
import pandas as pd
import os

***Input Directory and JSON files.***

In [2]:
inputDir = r'../Resource_Allocation_State_data'
AllocationFile = os.path.join(inputDir, 'Allocation.json')
MaxFile = os.path.join(inputDir, 'Max.json')
AvailableFile = os.path.join(inputDir, 'Available.json')

***Getting the Matrices: Allocation, Max, Available***

In [3]:
Allocation = pd.read_json(AllocationFile, orient='index').to_numpy()
Allocation

array([[0, 1, 0],
       [2, 0, 0],
       [3, 0, 2],
       [2, 1, 1],
       [0, 0, 2]], dtype=int64)

In [4]:
Max = pd.read_json(MaxFile, orient='index').to_numpy()
Max

array([[7, 5, 3],
       [3, 2, 2],
       [9, 0, 2],
       [2, 2, 2],
       [4, 3, 3]], dtype=int64)

In [5]:
Available = pd.read_json(AvailableFile, orient='index').to_numpy()[0]
Available

array([3, 3, 2], dtype=int64)

***Calculationg the Need Matrix***

In [6]:
Need = Max - Allocation
Need

array([[7, 4, 3],
       [1, 2, 2],
       [6, 0, 0],
       [0, 1, 1],
       [4, 3, 1]], dtype=int64)

***Safety Algorithm Starts: STEP 01***

In [7]:
# m = number of processes.
m = 5
Work = Available.copy()
Work

array([3, 3, 2], dtype=int64)

In [8]:
# Creation of Finish list.
Finish = [False for i in range(m)]
Finish

[False, False, False, False, False]

***STEP 02***

In [9]:
safe_sequence = []

while True:
    for i in range(m):
        if Finish[i] == False and np.all(Need[i,:] <= Work):
            Work += Allocation[i,:]
            Finish[i] = True
            safe_sequence.append(f'P{i}')
            
            print('\nResource State')  
            print(f'Available: {Work}')
            print(f'Finish State: {Finish}')
            print(f'safe_sequence: {safe_sequence}')

            continue
        else:
            Track = Finish.copy()
            
    
    if Track == Finish:
        break
    



Resource State
Available: [5 3 2]
Finish State: [False, True, False, False, False]
safe_sequence: ['P1']

Resource State
Available: [7 4 3]
Finish State: [False, True, False, True, False]
safe_sequence: ['P1', 'P3']

Resource State
Available: [7 4 5]
Finish State: [False, True, False, True, True]
safe_sequence: ['P1', 'P3', 'P4']

Resource State
Available: [7 5 5]
Finish State: [True, True, False, True, True]
safe_sequence: ['P1', 'P3', 'P4', 'P0']

Resource State
Available: [10  5  7]
Finish State: [True, True, True, True, True]
safe_sequence: ['P1', 'P3', 'P4', 'P0', 'P2']


***STEP 03***

In [10]:
if all(Finish):
    print(f'The System is safe. Safe Sequence - {safe_sequence}')
else:
    print('The System is NOT safe.')

The System is safe. Safe Sequence - ['P1', 'P3', 'P4', 'P0', 'P2']
